# https://help.github.com/en/articles/metadata-syntax-for-github-actions

author: 'Patrick Organ'

branding:
    icon: 'align-center'
    color: 'green'

description: 'Run ESLint on your source code from GitHub workflows'

name: 'ESLint Code Lint & Fix'

runs:
    using: 'docker'
    image: 'docker://permafrostsoftware/eslint-docker-ga:latest'
